name: Build Pull Request

on:
  pull_request:
    branches: [main]

concurrency:
   group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
   cancel-in-progress: true

jobs:

  cpp-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cpp-linter/cpp-linter-action@main
        id: linter
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: microsoft
          ignore: |
            include/argparse
          thread-comments: true
          format-review: true
          tidy-checks: '-*'

      - name: Fail fast?!
        if: steps.linter.outputs.checks-failed != 0
        run: |
          echo "some linter checks failed. ${{ steps.linter.outputs.checks-failed }}"
          exit 1

  build-n-test:
    runs-on: [gpu]

    container:
      image: ghcr.io/bnlnpps/esi-shell:1.4.3-devel
      volumes:
        - /usr/local/optix:/usr/local/optix
      options: -i -t

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        shell: bash
        run: |
          cmake -S . -B build
          cmake --build build

      - name: Test
        shell: bash
        env:
          GEOM: fakegeom
          OPTICKS_EVENT_MODE: DebugLite
          OPTICKS_MAX_SLOT: 1000000
        run: |
          QCurandStateMonolithic_SPEC=3:0:0  $OPTICKS_PREFIX/lib/QCurandStateMonolithicTest
          mv $HOME/.opticks/rngcache/RNG/QCurandStateMonolithic_3M_0_0.bin $HOME/.opticks/rngcache/RNG/QCurandState_3000000_0_0.bin
          build/src/simtox
          build/src/simg4ox -g geom/raindrop.gdml -m run.mac
          ls -la /tmp/GEOM/fakegeom/simg4ox/ALL0_none/A000
          ls -la /tmp/GEOM/fakegeom/simg4ox/ALL0_none/B000/f000
          python tests/compare_ab.py
          build/src/simg4ox -g geom/basic_detector.gdml -m run.mac
